<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Campu extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Campu_model');
    } 

    /*
     * Listing of campus
     */
    function index()
    {
        $data['campus'] = $this->Campu_model->get_all_campus();
        
        $data['_view'] = 'campu/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new campu
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'nome' => $this->input->post('nome'),
            );
            
            $campu_id = $this->Campu_model->add_campu($params);
            redirect('campu/index');
        }
        else
        {            
            $data['_view'] = 'campu/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a campu
     */
    function edit($id)
    {   
        // check if the campu exists before trying to edit it
        $data['campu'] = $this->Campu_model->get_campu($id);
        
        if(isset($data['campu']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'nome' => $this->input->post('nome'),
                );

                $this->Campu_model->update_campu($id,$params);            
                redirect('campu/index');
            }
            else
            {
                $data['_view'] = 'campu/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The campu you are trying to edit does not exist.');
    } 

    /*
     * Deleting campu
     */
    function remove($id)
    {
        $campu = $this->Campu_model->get_campu($id);

        // check if the campu exists before trying to delete it
        if(isset($campu['id']))
        {
            $this->Campu_model->delete_campu($id);
            redirect('campu/index');
        }
        else
            show_error('The campu you are trying to delete does not exist.');
    }
    
}
