<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Checklist extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Checklist_model');
    } 

    /*
     * Listing of checklist
     */
    function index()
    {
        $data['checklist'] = $this->Checklist_model->get_all_checklist();
        
        $data['_view'] = 'checklist/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new checklist
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'disciplina_id' => $this->input->post('disciplina_id'),
				'nome' => $this->input->post('nome'),
				'valor' => $this->input->post('valor'),
				'tipo' => $this->input->post('tipo'),
            );
            
            $checklist_id = $this->Checklist_model->add_checklist($params);
            redirect('checklist/index');
        }
        else
        {            
            $data['_view'] = 'checklist/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a checklist
     */
    function edit($id)
    {   
        // check if the checklist exists before trying to edit it
        $data['checklist'] = $this->Checklist_model->get_checklist($id);
        
        if(isset($data['checklist']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'disciplina_id' => $this->input->post('disciplina_id'),
					'nome' => $this->input->post('nome'),
					'valor' => $this->input->post('valor'),
					'tipo' => $this->input->post('tipo'),
                );

                $this->Checklist_model->update_checklist($id,$params);            
                redirect('checklist/index');
            }
            else
            {
                $data['_view'] = 'checklist/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The checklist you are trying to edit does not exist.');
    } 

    /*
     * Deleting checklist
     */
    function remove($id)
    {
        $checklist = $this->Checklist_model->get_checklist($id);

        // check if the checklist exists before trying to delete it
        if(isset($checklist['id']))
        {
            $this->Checklist_model->delete_checklist($id);
            redirect('checklist/index');
        }
        else
            show_error('The checklist you are trying to delete does not exist.');
    }
    
}
