<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contato extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Contato_model');
    } 

    /*
     * Listing of contato
     */
    function index()
    {
        $data['contato'] = $this->Contato_model->get_all_contato();
        
        $data['_view'] = 'contato/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new contato
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'usuario_id' => $this->input->post('usuario_id'),
				'tipo' => $this->input->post('tipo'),
				'ddd' => $this->input->post('ddd'),
				'numero' => $this->input->post('numero'),
            );
            
            $contato_id = $this->Contato_model->add_contato($params);
            redirect('contato/index');
        }
        else
        {            
            $data['_view'] = 'contato/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a contato
     */
    function edit($id)
    {   
        // check if the contato exists before trying to edit it
        $data['contato'] = $this->Contato_model->get_contato($id);
        
        if(isset($data['contato']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'usuario_id' => $this->input->post('usuario_id'),
					'tipo' => $this->input->post('tipo'),
					'ddd' => $this->input->post('ddd'),
					'numero' => $this->input->post('numero'),
                );

                $this->Contato_model->update_contato($id,$params);            
                redirect('contato/index');
            }
            else
            {
                $data['_view'] = 'contato/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The contato you are trying to edit does not exist.');
    } 

    /*
     * Deleting contato
     */
    function remove($id)
    {
        $contato = $this->Contato_model->get_contato($id);

        // check if the contato exists before trying to delete it
        if(isset($contato['id']))
        {
            $this->Contato_model->delete_contato($id);
            redirect('contato/index');
        }
        else
            show_error('The contato you are trying to delete does not exist.');
    }
    
}
