<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Disponibilidade extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Disponibilidade_model');
    } 

    /*
     * Listing of disponibilidade
     */
    function index()
    {
        $data['disponibilidade'] = $this->Disponibilidade_model->get_all_disponibilidade();
        
        $data['_view'] = 'disponibilidade/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new disponibilidade
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'dt_inicio' => $this->input->post('dt_inicio'),
				'dt_fim' => $this->input->post('dt_fim'),
				'laboratorio_id' => $this->input->post('laboratorio_id'),
            );
            
            $disponibilidade_id = $this->Disponibilidade_model->add_disponibilidade($params);
            redirect('disponibilidade/index');
        }
        else
        {            
            $data['_view'] = 'disponibilidade/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a disponibilidade
     */
    function edit($id)
    {   
        // check if the disponibilidade exists before trying to edit it
        $data['disponibilidade'] = $this->Disponibilidade_model->get_disponibilidade($id);
        
        if(isset($data['disponibilidade']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'dt_inicio' => $this->input->post('dt_inicio'),
					'dt_fim' => $this->input->post('dt_fim'),
					'laboratorio_id' => $this->input->post('laboratorio_id'),
                );

                $this->Disponibilidade_model->update_disponibilidade($id,$params);            
                redirect('disponibilidade/index');
            }
            else
            {
                $data['_view'] = 'disponibilidade/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The disponibilidade you are trying to edit does not exist.');
    } 

    /*
     * Deleting disponibilidade
     */
    function remove($id)
    {
        $disponibilidade = $this->Disponibilidade_model->get_disponibilidade($id);

        // check if the disponibilidade exists before trying to delete it
        if(isset($disponibilidade['id']))
        {
            $this->Disponibilidade_model->delete_disponibilidade($id);
            redirect('disponibilidade/index');
        }
        else
            show_error('The disponibilidade you are trying to delete does not exist.');
    }
    
}
