<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itens_laboratorio extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Itens_laboratorio_model');
    } 

    /*
     * Listing of itens_laboratorio
     */
    function index()
    {
        $data['itens_laboratorio'] = $this->Itens_laboratorio_model->get_all_itens_laboratorio();
        
        $data['_view'] = 'itens_laboratorio/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new itens_laboratorio
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'chk_projeto' => $this->input->post('chk_projeto'),
				'laboratorio_id' => $this->input->post('laboratorio_id'),
				'qtd_maquinas' => $this->input->post('qtd_maquinas'),
            );
            
            $itens_laboratorio_id = $this->Itens_laboratorio_model->add_itens_laboratorio($params);
            redirect('itens_laboratorio/index');
        }
        else
        {            
            $data['_view'] = 'itens_laboratorio/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a itens_laboratorio
     */
    function edit($id)
    {   
        // check if the itens_laboratorio exists before trying to edit it
        $data['itens_laboratorio'] = $this->Itens_laboratorio_model->get_itens_laboratorio($id);
        
        if(isset($data['itens_laboratorio']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'chk_projeto' => $this->input->post('chk_projeto'),
					'laboratorio_id' => $this->input->post('laboratorio_id'),
					'qtd_maquinas' => $this->input->post('qtd_maquinas'),
                );

                $this->Itens_laboratorio_model->update_itens_laboratorio($id,$params);            
                redirect('itens_laboratorio/index');
            }
            else
            {
                $data['_view'] = 'itens_laboratorio/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The itens_laboratorio you are trying to edit does not exist.');
    } 

    /*
     * Deleting itens_laboratorio
     */
    function remove($id)
    {
        $itens_laboratorio = $this->Itens_laboratorio_model->get_itens_laboratorio($id);

        // check if the itens_laboratorio exists before trying to delete it
        if(isset($itens_laboratorio['id']))
        {
            $this->Itens_laboratorio_model->delete_itens_laboratorio($id);
            redirect('itens_laboratorio/index');
        }
        else
            show_error('The itens_laboratorio you are trying to delete does not exist.');
    }
    
}
