<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Preferencium extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Preferencium_model');
    } 

    /*
     * Listing of preferencia
     */
    function index()
    {
        $data['preferencia'] = $this->Preferencium_model->get_all_preferencia();
        
        $data['_view'] = 'preferencium/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new preferencium
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'preferencia' => $this->input->post('preferencia'),
				'valor' => $this->input->post('valor'),
				'descricao' => $this->input->post('descricao'),
            );
            
            $preferencium_id = $this->Preferencium_model->add_preferencium($params);
            redirect('preferencium/index');
        }
        else
        {            
            $data['_view'] = 'preferencium/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a preferencium
     */
    function edit($id)
    {   
        // check if the preferencium exists before trying to edit it
        $data['preferencium'] = $this->Preferencium_model->get_preferencium($id);
        
        if(isset($data['preferencium']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'preferencia' => $this->input->post('preferencia'),
					'valor' => $this->input->post('valor'),
					'descricao' => $this->input->post('descricao'),
                );

                $this->Preferencium_model->update_preferencium($id,$params);            
                redirect('preferencium/index');
            }
            else
            {
                $data['_view'] = 'preferencium/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The preferencium you are trying to edit does not exist.');
    } 

    /*
     * Deleting preferencium
     */
    function remove($id)
    {
        $preferencium = $this->Preferencium_model->get_preferencium($id);

        // check if the preferencium exists before trying to delete it
        if(isset($preferencium['id']))
        {
            $this->Preferencium_model->delete_preferencium($id);
            redirect('preferencium/index');
        }
        else
            show_error('The preferencium you are trying to delete does not exist.');
    }
    
}
