<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Auditorium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get auditorium by id
     */
    function get_auditorium($id)
    {
        return $this->db->get_where('auditoria',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all auditoria
     */
    function get_all_auditoria()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('auditoria')->result_array();
    }
        
    /*
     * function to add new auditorium
     */
    function add_auditorium($params)
    {
        $this->db->insert('auditoria',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update auditorium
     */
    function update_auditorium($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('auditoria',$params);
    }
    
    /*
     * function to delete auditorium
     */
    function delete_auditorium($id)
    {
        return $this->db->delete('auditoria',array('id'=>$id));
    }
}
