<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Campu_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get campu by id
     */
    function get_campu($id)
    {
        return $this->db->get_where('campus',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all campus
     */
    function get_all_campus()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('campus')->result_array();
    }
        
    /*
     * function to add new campu
     */
    function add_campu($params)
    {
        $this->db->insert('campus',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update campu
     */
    function update_campu($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('campus',$params);
    }
    
    /*
     * function to delete campu
     */
    function delete_campu($id)
    {
        return $this->db->delete('campus',array('id'=>$id));
    }
}
