<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Checklist_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get checklist by id
     */
    function get_checklist($id)
    {
        return $this->db->get_where('checklist',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all checklist
     */
    function get_all_checklist()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('checklist')->result_array();
    }
        
    /*
     * function to add new checklist
     */
    function add_checklist($params)
    {
        $this->db->insert('checklist',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update checklist
     */
    function update_checklist($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('checklist',$params);
    }
    
    /*
     * function to delete checklist
     */
    function delete_checklist($id)
    {
        return $this->db->delete('checklist',array('id'=>$id));
    }
}
