<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Contato_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get contato by id
     */
    function get_contato($id)
    {
        return $this->db->get_where('contato',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all contato
     */
    function get_all_contato()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('contato')->result_array();
    }
        
    /*
     * function to add new contato
     */
    function add_contato($params)
    {
        $this->db->insert('contato',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update contato
     */
    function update_contato($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('contato',$params);
    }
    
    /*
     * function to delete contato
     */
    function delete_contato($id)
    {
        return $this->db->delete('contato',array('id'=>$id));
    }
}
