<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Disciplina_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get disciplina by id
     */
    function get_disciplina($id)
    {
        return $this->db->get_where('disciplina',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all disciplina
     */
    function get_all_disciplina()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('disciplina')->result_array();
    }
        
    /*
     * function to add new disciplina
     */
    function add_disciplina($params)
    {
        $this->db->insert('disciplina',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update disciplina
     */
    function update_disciplina($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('disciplina',$params);
    }
    
    /*
     * function to delete disciplina
     */
    function delete_disciplina($id)
    {
        return $this->db->delete('disciplina',array('id'=>$id));
    }
}
