<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Disponibilidade_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get disponibilidade by id
     */
    function get_disponibilidade($id)
    {
        return $this->db->get_where('disponibilidade',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all disponibilidade
     */
    function get_all_disponibilidade()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('disponibilidade')->result_array();
    }
        
    /*
     * function to add new disponibilidade
     */
    function add_disponibilidade($params)
    {
        $this->db->insert('disponibilidade',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update disponibilidade
     */
    function update_disponibilidade($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('disponibilidade',$params);
    }
    
    /*
     * function to delete disponibilidade
     */
    function delete_disponibilidade($id)
    {
        return $this->db->delete('disponibilidade',array('id'=>$id));
    }
}
