<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itens_laboratorio_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get itens_laboratorio by id
     */
    function get_itens_laboratorio($id)
    {
        return $this->db->get_where('itens_laboratorio',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all itens_laboratorio
     */
    function get_all_itens_laboratorio()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('itens_laboratorio')->result_array();
    }
        
    /*
     * function to add new itens_laboratorio
     */
    function add_itens_laboratorio($params)
    {
        $this->db->insert('itens_laboratorio',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update itens_laboratorio
     */
    function update_itens_laboratorio($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('itens_laboratorio',$params);
    }
    
    /*
     * function to delete itens_laboratorio
     */
    function delete_itens_laboratorio($id)
    {
        return $this->db->delete('itens_laboratorio',array('id'=>$id));
    }
}
