<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Itens_reserva_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get itens_reserva by reserva_id
     */
    function get_itens_reserva($reserva_id)
    {
        return $this->db->get_where('itens_reserva',array('reserva_id'=>$reserva_id))->row_array();
    }
        
    /*
     * Get all itens_reserva
     */
    function get_all_itens_reserva()
    {
        $this->db->order_by('reserva_id', 'desc');
        return $this->db->get('itens_reserva')->result_array();
    }
        
    /*
     * function to add new itens_reserva
     */
    function add_itens_reserva($params)
    {
        $this->db->insert('itens_reserva',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update itens_reserva
     */
    function update_itens_reserva($reserva_id,$params)
    {
        $this->db->where('reserva_id',$reserva_id);
        return $this->db->update('itens_reserva',$params);
    }
    
    /*
     * function to delete itens_reserva
     */
    function delete_itens_reserva($reserva_id)
    {
        return $this->db->delete('itens_reserva',array('reserva_id'=>$reserva_id));
    }
}
