<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Preferencium_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get preferencium by id
     */
    function get_preferencium($id)
    {
        return $this->db->get_where('preferencia',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all preferencia
     */
    function get_all_preferencia()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('preferencia')->result_array();
    }
        
    /*
     * function to add new preferencium
     */
    function add_preferencium($params)
    {
        $this->db->insert('preferencia',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update preferencium
     */
    function update_preferencium($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('preferencia',$params);
    }
    
    /*
     * function to delete preferencium
     */
    function delete_preferencium($id)
    {
        return $this->db->delete('preferencia',array('id'=>$id));
    }
}
